// mqtt_tls_bench.ino - Stage 2, the pipeline and the key-exchange sweep on the Pico W / Pico 2 W: MQTT 3.1.1 over
//   plain TCP, TLS 1.3 and mutual TLS (wolfSSL 5.9.4, X25519MLKEM768) over Wi-Fi to the Mosquitto brokers of
//   ./run_all.sh --serve-broker on another machine. Same packets, sequence and CSV rows as the host client
//   network/mqtt_tls_timer.c, so run_benchmarks.py summarises them with the host's code:
//     connect  per connection: TCP connect | TLS handshake | MQTT CONNECT..CONNACK, bytes and socket calls
//     pipeline per message:    a 51 B reading sealed in a LoRaWAN data frame (lora_aead.h: none, LoRaWAN 1.0.x /
//                              1.1, AES-256-CTR+CMAC, AES-128/256-GCM, AES-128/256-CCM, Ascon-AEAD128; uplink and
//                              downlink frames), PUBLISHed to the
//                              broker, back down to this client's SUBSCRIBE, verified + decrypted (the host's
//                              --messages run). LoRaWAN / AES / Ascon are measured only this way: through the broker.
//     sweep    per connection, as connect, for every key exchange in GROUPS (the host's tls stage,
//              tls_sweep.sh, against the same listeners): TLS and mTLS
//     kex      (-DMT_KEX_ONLY firmware: only these blocks) the KEM exchange as MQTT messages through the broker's plain
//              listener, as the host's --kex (mqtt_tls_timer.c kem_exchange): per KEM in kem_wolf.h a key pair here,
//              the public key PUBLISHed, the responder next to the broker encapsulates, the ciphertext comes back and
//              is decapsulated here. ML-KEM-512/768/1024, X25519 and the customer's X25519MLKEM768 (wolfCrypt)
//   One certificate algorithm per firmware (-DWB_TLS -DWB_<ALG> -DMT_SIG=<certs/ dir>). mt_secrets.h
//   (Wi-Fi, broker, ports, that CA / client cert / key as DER) is generated by the runner from WIFI_SSID,
//   WIFI_PASS and BROKER; the firmware holds them, so the runner deletes its build.
//   No TCP segment counts (lwIP keeps none per socket): the host's wire_* estimate has no Pico column.
//   Wi-Fi power save is off (as TCP_NODELAY on the host: latency is what is measured).
//   Each connection row also splits the handshake's own crypto on this board (hs_timing.c, --wrap): key share
//   generation, its completion (decapsulation / shared secret), signature verification and signing, with counts.
//   Output: '#block <stage> <mode> [<scheme> <up|down> | <group>]' .. '#end' per block. stage = connect (Stage 2, one
//   row per connection), pipeline (+ one row per message) or sweep; mode = the transport: plain, TLS (server-auth)
//   or mTLS.
//   The run is on a 16 KB painted stack (the Wi-Fi interrupts use it too): '#stack' is the block's peak, 1.5-2.8 KB
//   so far. A hardware watchdog (8 s without progress) reboots a hung board; it then reports '#watchdog <block>:
//   hung during <step> (connection n)' - the step is kept in a watchdog scratch register - and carries on
//   with the next block. Each row also carries the free heap before that connection (a leak = a falling column).

#include <Arduino.h>
#include <WiFi.h>
#include <wolfssl.h>
#include <wolfssl/ssl.h>
#include <hardware/structs/watchdog.h>  // scratch registers survive a watchdog reboot: which block hung
#include "mt_secrets.h"
#include "lora_aead.h"
#include "kem_wolf.h"
#include "hs_timing.h"  // the client's crypto inside each handshake (hs_timing.c, linked with --wrap)
#include <wolfssl/wolfcrypt/hash.h>
#ifdef CURVE25519_SMALL  // wolfSSL's small, slow Curve25519 code (-DWB_SMALL_25519, the A/B); default: its normal code
#define X25519_BUILD "_(small_X25519)"  // lib= has no spaces: _ reads as one
#else
#define X25519_BUILD ""
#endif

#if defined(__ARM_ARCH_6M__)
#define CHIP "RP2040"
#else
#define CHIP "RP2350"
#endif
#define STR_(x) #x
#define STR(x) STR_(x)
// the host's defaults: mqtt_bench.py 50 connections + 5 warm-up; pipeline 3 + 1, run_all.sh 200 messages
#ifndef MT_ITERS
#define MT_ITERS 50
#endif
#ifndef MT_WARMUP
#define MT_WARMUP 5
#endif
#ifndef MT_PIPE_ITERS
#define MT_PIPE_ITERS 3
#endif
#ifndef MT_MSGS
#define MT_MSGS 200
#endif
#ifndef MT_PAYLOAD
#define MT_PAYLOAD 51
#endif
// the sweep: fewer than the host's 200 + 20 (a Pico connection takes ~1-2 s; its spread is ~1 %)
#ifndef MT_SWEEP_ITERS
#define MT_SWEEP_ITERS 20
#endif
#ifndef MT_SWEEP_WARMUP
#define MT_SWEEP_WARMUP 2
#endif
// the KEM exchange: the host's --kex-n 50 + 2 warm-up, all on one connection
#ifndef MT_KEX_ITERS
#define MT_KEX_ITERS 50
#endif
#ifndef MT_KEX_WARMUP
#define MT_KEX_WARMUP 2
#endif
// one connection; bytes and socket calls are counted where they cross WiFiClient (raw_send / raw_recv).
// Above the first function: the .ino preprocessor puts its prototypes there.
struct Conn { WiFiClient cl; uint32_t tx = 0, rx = 0, io[2] = {0, 0}; WOLFSSL *tls = nullptr; };
struct Block { const char *stage, *mode; int iters, warm, msgs, aead, down, group; };
struct Group { const char *name; int id; };
// mqtt_bench.SWEEP_GROUPS by their OpenSSL names, those wolfSSL has (not HQC, FrodoKEM)
static const Group GROUPS[] = {
  {"MLKEM512", WOLFSSL_ML_KEM_512}, {"MLKEM768", WOLFSSL_ML_KEM_768}, {"MLKEM1024", WOLFSSL_ML_KEM_1024},
  {"X25519MLKEM768", WOLFSSL_X25519MLKEM768}, {"SecP256r1MLKEM768", WOLFSSL_SECP256R1MLKEM768},
  {"SecP384r1MLKEM1024", WOLFSSL_SECP384R1MLKEM1024},
  {"SecP256r1MLKEM512", WOLFSSL_SECP256R1MLKEM512}, {"x25519_mlkem512", WOLFSSL_X25519MLKEM512},
  {"p384_mlkem768", WOLFSSL_SECP384R1MLKEM768}, {"p521_mlkem1024", WOLFSSL_SECP521R1MLKEM1024},
  {"x448_mlkem768", WOLFSSL_X448MLKEM768},
  {"X25519", WOLFSSL_ECC_X25519}, {"secp256r1", WOLFSSL_ECC_SECP256R1}};
enum { N_GROUPS = sizeof GROUPS / sizeof *GROUPS, G_STAGE2 = 3 };  // Stage 2 / pipeline: X25519MLKEM768
static const char *const MODES[] = {"plain", "TLS", "mTLS"};
// connect x 3 modes, pipeline x 3 modes x 10 schemes x up / down, then sweep x TLS / mTLS x every group
#ifdef MT_KEX_ONLY
enum { N_BLOCKS = KW_N };  // one kex block per KEM
#else
enum { N_BLOCKS = 3 + 3 * LA_N * 2 + 2 * N_GROUPS };
#endif
static const uint32_t RESUME_MAGIC = 0x4D515454;  // watchdog scratch[1]: scratch[0] holds a valid block index
// the step in progress (scratch[2]) and the connection (scratch[3], < 0 = warm-up): a reboot reports where it hung
static const char *const STEPS[] = {"setup", "TCP connect", "TLS handshake", "MQTT CONNECT", "SUBSCRIBE",
                                    "PUBLISH / echo", "TLS close", "TCP close", "serial output", "key pair",
                                    "decapsulation"};
enum { S_SETUP, S_TCP, S_TLS, S_MQTT, S_SUB, S_PUB, S_TLSCLOSE, S_TCPCLOSE, S_SERIAL, S_KEYGEN, S_DECAPS };
#define STEP(x) (watchdog_hw->scratch[2] = (x))

// ---- big painted stack + stack-pointer switch, as liboqs_bench (validated on both boards) ----
#define MT_STACK_KB 16
#define STK_PAT 0x5A
static uint8_t g_stk[MT_STACK_KB * 1024u] __attribute__((aligned(16)));
#if defined(__ARM_ARCH_8M_MAIN__) || defined(__ARM_ARCH_8M_BASE__)
__attribute__((naked, noinline)) static int run_on_stack(void *new_top, int (*fn)(void)) {  // M33
  __asm volatile(
    "mrs  r2, msplim       \n"
    "mov  r3, sp           \n"
    "mov  sp, r0           \n"
    "movs r0, #0           \n"
    "msr  msplim, r0       \n"
    "push {r2, r3, r4, lr} \n"
    "blx  r1               \n"
    "pop  {r2, r3, r4, lr} \n"
    "msr  msplim, r2       \n"
    "mov  sp, r3           \n"
    "bx   lr               \n");
}
#else
__attribute__((naked, noinline)) static int run_on_stack(void *new_top, int (*fn)(void)) {  // M0+
  __asm volatile(
    "mov  r2, sp   \n"
    "mov  sp, r0   \n"
    "push {r2, lr} \n"
    "blx  r1       \n"
    "pop  {r2, r3} \n"
    "mov  sp, r2   \n"
    "bx   r3       \n");
}
#endif
static uint32_t stack_peak() {
  uint32_t i = 0; while (i < sizeof g_stk && g_stk[i] == STK_PAT) i++;
  return sizeof g_stk - i;
}

extern "C" int wb_rand_block(unsigned char *out, unsigned int n) {
  while (n >= 4) { uint32_t r = rp2040.hwrand32(); memcpy(out, &r, 4); out += 4; n -= 4; }
  if (n) { uint32_t r = rp2040.hwrand32(); memcpy(out, &r, n); }
  return 0;
}

// ---- wolfSSL heap accounting (as wolfssl_bench): the peak is the TLS working set ----
static size_t cur_heap, peak_heap;
typedef union { size_t n; long long align; } hdr_t;
static void *wb_malloc(size_t n) {
  hdr_t *h = (hdr_t *)malloc(n + sizeof(hdr_t));
  if (!h) return NULL;
  h->n = n; cur_heap += n; if (cur_heap > peak_heap) peak_heap = cur_heap;
  return h + 1;
}
static void wb_free(void *p) {
  if (!p) return;
  hdr_t *h = (hdr_t *)p - 1; cur_heap -= h->n; free(h);
}
static void *wb_realloc(void *p, size_t n) {
  if (!p) return wb_malloc(n);
  hdr_t *h = (hdr_t *)p - 1; size_t old = h->n;
  hdr_t *nh = (hdr_t *)realloc(h, n + sizeof(hdr_t));
  if (!nh) return NULL;
  nh->n = n; cur_heap = cur_heap - old + n; if (cur_heap > peak_heap) peak_heap = cur_heap;
  return nh + 1;
}

static IPAddress broker;
static char err[160];
static bool kat_ok;  // lora_aead.h's known-answer checks passed: the pipeline's schemes can be trusted

static Block plan(int i) {  // connect; per mode every scheme, uplink then downlink; per mode every group
#ifdef MT_KEX_ONLY
  return {"kex", "plain", 1, 0, 0, -1, 0, i};  // group = the KEM (KW[i]); one connection, MT_KEX_ITERS exchanges
#endif
  if (i < 3) return {"connect", MODES[i], MT_ITERS, MT_WARMUP, 0, -1, 0, G_STAGE2};
  i -= 3;
  if (i < 3 * LA_N * 2) return {"pipeline", MODES[i / (2 * LA_N)], MT_PIPE_ITERS, 1, MT_MSGS, i / 2 % LA_N, i % 2, G_STAGE2};
  i -= 3 * LA_N * 2;
  return {"sweep", MODES[1 + i / N_GROUPS], MT_SWEEP_ITERS, MT_SWEEP_WARMUP, 0, -1, 0, i % N_GROUPS};
}
static const char *label(const Block &b) {  // "connect TLS", "pipeline mTLS lorawan11 down", "sweep TLS MLKEM512"
  static char l[64];
  if (!strcmp(b.stage, "sweep")) snprintf(l, sizeof l, "%s %s %s", b.stage, b.mode, GROUPS[b.group].name);
  else if (!strcmp(b.stage, "kex")) snprintf(l, sizeof l, "%s %s %s", b.stage, b.mode, KW[b.group].name);
  else if (b.aead < 0) snprintf(l, sizeof l, "%s %s", b.stage, b.mode);
  else snprintf(l, sizeof l, "%s %s %s %s", b.stage, b.mode, LA[b.aead].name, b.down ? "down" : "up");
  return l;
}

static int raw_send(Conn *c, const uint8_t *b, int n) {
  rp2040.wdt_reset();
  int r = (int)c->cl.write(b, n);
  if (r > 0) { c->tx += r; c->io[0]++; }
  return r;
}
static int raw_recv(Conn *c, uint8_t *b, int n) {  // 0 = closed, -1 = 10 s silence (the host's SO_RCVTIMEO)
  for (uint32_t t0 = millis(); !c->cl.available();) {
    rp2040.wdt_reset();
    if (!c->cl.connected()) return 0;
    if (millis() - t0 > 10000) return -1;
  }
  int r = c->cl.read(b, n);
  if (r > 0) { c->rx += r; c->io[1]++; }
  return r;
}
static int cb_send(WOLFSSL *, char *b, int n, void *c) {
  int r = raw_send((Conn *)c, (const uint8_t *)b, n);
  return r > 0 ? r : WOLFSSL_CBIO_ERR_CONN_CLOSE;
}
static int cb_recv(WOLFSSL *, char *b, int n, void *c) {
  int r = raw_recv((Conn *)c, (uint8_t *)b, n);
  return r > 0 ? r : r == 0 ? WOLFSSL_CBIO_ERR_CONN_CLOSE : WOLFSSL_CBIO_ERR_TIMEOUT;
}
static const char *tls_err(Conn *c, int r) {
  static char e[WOLFSSL_MAX_ERROR_SZ];
  return c->tls ? wolfSSL_ERR_error_string(wolfSSL_get_error(c->tls, r), e) : "connection closed by broker";
}

// ---- MQTT, as mqtt_tls_timer.c ----
static int io_write(Conn *c, const uint8_t *b, int n) { return c->tls ? wolfSSL_write(c->tls, b, n) : raw_send(c, b, n); }
static int io_read_n(Conn *c, uint8_t *b, int n) {
  for (int got = 0, r; got < n; got += r)
    if ((r = c->tls ? wolfSSL_read(c->tls, b + got, n - got) : raw_recv(c, b + got, n - got)) <= 0) return r;
  return n;
}
static int read_packet(Conn *c, uint8_t *type, uint8_t *body, int cap) {  // body length, -1 on error
  int len = 0, shift = 0;
  uint8_t b;
  if (io_read_n(c, type, 1) != 1) return -1;
  do {
    if (io_read_n(c, &b, 1) != 1 || shift > 21) return -1;
    len |= (b & 0x7F) << shift; shift += 7;
  } while (b & 0x80);
  return len <= cap && io_read_n(c, body, len) == len ? len : -1;
}
static int put_len(uint8_t *p, int len) {
  int n = 0;
  do { p[n] = len & 0x7F; len >>= 7; if (len) p[n] |= 0x80; n++; } while (len);
  return n;
}
static int connect_packet(uint8_t *p, const char *id, int keepalive) {
  int il = (int)strlen(id), n = 0;
  p[n++] = 0x10; n += put_len(p + n, 10 + 2 + il);
  memcpy(p + n, "\0\4MQTT\4\2", 8); n += 8;
  p[n++] = keepalive >> 8; p[n++] = keepalive & 0xFF;
  p[n++] = il >> 8; p[n++] = il & 0xFF; memcpy(p + n, id, il);
  return n + il;
}
static bool subscribe(Conn *c, const char *filter) {  // QoS 0, packet id 1, waits for SUBACK
  static uint8_t pkt[128], body[16];
  int tl = (int)strlen(filter), n = 0;
  uint8_t type;
  pkt[n++] = 0x82; n += put_len(pkt + n, 2 + 2 + tl + 1);
  pkt[n++] = 0; pkt[n++] = 1;
  pkt[n++] = tl >> 8; pkt[n++] = tl & 0xFF; memcpy(pkt + n, filter, tl); n += tl;
  pkt[n++] = 0;
  return io_write(c, pkt, n) == n && read_packet(c, &type, body, sizeof body) >= 0 && type == 0x90;
}

// the pipeline: seal a reading with the block's scheme (lora_aead.h; the frame, FCnt and direction as the host's
// app_seal), PUBLISH it, wait for the broker to deliver it back, then verify + decrypt it (app_open)
static char topic[32];
static int cur_aead;
static const char *pipeline(Conn *c, int iter, int msgs, bool report) {
  static uint8_t pkt[64 + sizeof frame], body[64 + sizeof frame];
  const la_scheme &sc = LA[cur_aead];
  int tl = (int)strlen(topic), fl = HDR + MT_PAYLOAD + sc.tag;
  uint8_t type;
  STEP(S_SUB);
  if (!subscribe(c, topic)) return "mqtt subscribe failed: no SUBACK";
  for (int m = 0; m < msgs; m++) {
    char s[48];
    int sl = snprintf(s, sizeof s, "{\"seq\":%lu,\"temp_c\":21.5,\"rh\":48}", (unsigned long)(fcnt + 1));
    memset(pt, ' ', MT_PAYLOAD);
    memcpy(pt, s, sl < MT_PAYLOAD ? sl : MT_PAYLOAD);
    uint32_t t0 = micros();
    if (sc.seal(MT_PAYLOAD)) return "seal failed";
    uint32_t t1 = micros();
    int h = 0;
    pkt[h++] = 0x30; h += put_len(pkt + h, 2 + tl + fl);
    pkt[h++] = tl >> 8; pkt[h++] = tl & 0xFF;
    memcpy(pkt + h, topic, tl); memcpy(pkt + h + tl, frame, fl);
    int n = h + tl + fl, len;
    uint32_t tx0 = c->tx, rx0 = c->rx;
    STEP(S_PUB);
    if (io_write(c, pkt, n) != n) return "mqtt publish failed: write";
    do len = read_packet(c, &type, body, sizeof body);  // skip anything that isn't our PUBLISH
    while (len >= 0 && (type & 0xF0) != 0x30);
    uint32_t t2 = micros();
    if (len < 2) return "mqtt publish failed: no echo from broker";
    int off = 2 + (body[0] << 8 | body[1]);
    bool ok = len - off == fl;
    if (ok) { memcpy(frame, body + off, fl); ok = sc.open(MT_PAYLOAD) == 0 && !memcmp(out, pt, MT_PAYLOAD); }
    uint32_t t3 = micros();
    if (!ok) { snprintf(err, sizeof err, "payload verification failed: %s", sc.name); return err; }
    STEP(S_SERIAL);
    if (report) Serial.printf("msg,%d,%d,%lu,%lu,%lu,%lu,%lu\n", iter, m, (unsigned long)(t1 - t0),
                              (unsigned long)(t2 - t1), (unsigned long)(t3 - t2),
                              (unsigned long)(c->tx - tx0), (unsigned long)(c->rx - rx0));
  }
  return nullptr;
}

// the KEM exchange, as mqtt_tls_timer.c kem_exchange: a key pair here, the public key PUBLISHed on
// pqc/kem/<id>/pk/<KEM>, the responder replies on pqc/kem/<id>/ct with ciphertext | SHA-256(secret) | its
// encapsulation time (4 B LE, us); decapsulate and compare the hashes (key confirmation). Rows as the host's:
//   kex,iter,idx,keygen_us,rtt_us,decaps_us,encaps_us,tx_B,rx_B    (rtt: PUBLISH of the key -> ciphertext back)
static int cur_kem = -1;
#ifdef MT_KEX_ONLY  // only in that firmware: the TLS ones stay as they were measured
static const char *kem_exchange(Conn *c) {
  static kw_state s;  // static: the ML-KEM key is kilobytes, the block runs on a 16 KB stack
  static WC_RNG rng;
  static uint8_t pk[KW_MAX], ss[64], h[WC_SHA256_DIGEST_SIZE], pkt[KW_MAX + 96], body[KW_MAX + 96];
  char pk_topic[64], ct_topic[48];
  snprintf(pk_topic, sizeof pk_topic, "pqc/kem/%s/pk/%s", topic + 9, KW[cur_kem].name);  // topic + 9 = "pico-<devaddr>"
  snprintf(ct_topic, sizeof ct_topic, "pqc/kem/%s/ct", topic + 9);
  if (wc_InitRng(&rng) || kw_init(&s, cur_kem, &rng)) return "wolfCrypt RNG / ML-KEM init failed";
  Serial.printf("#kem %s lib=wolfSSL_%s%s pk_B=%lu ct_B=%lu ss_B=%lu nist_level=%d\n", s.k->name,
                LIBWOLFSSL_VERSION_STRING, s.k->x25519 ? X25519_BUILD : "", (unsigned long)s.pk, (unsigned long)s.ct,
                (unsigned long)s.ss, s.k->level);
  Serial.println("kex,iter,idx,keygen_us,rtt_us,decaps_us,encaps_us,tx_B,rx_B");
  const char *e = nullptr;
  int tl = (int)strlen(pk_topic);
  STEP(S_SUB);
  if (!subscribe(c, ct_topic)) e = "mqtt subscribe failed: no SUBACK";
  for (int x = 0; x < MT_KEX_WARMUP + MT_KEX_ITERS && !e; x++) {
    rp2040.wdt_reset();
    watchdog_hw->scratch[3] = (uint32_t)(x - MT_KEX_WARMUP);
    STEP(S_KEYGEN);
    uint32_t t0 = micros();
    if (kw_keypair(&s, pk)) { e = "key pair failed"; break; }
    uint32_t ta = micros();
    int n = 0, len;
    pkt[n++] = 0x30; n += put_len(pkt + n, 2 + tl + (int)s.pk);
    pkt[n++] = tl >> 8; pkt[n++] = tl & 0xFF; memcpy(pkt + n, pk_topic, tl); memcpy(pkt + n + tl, pk, s.pk);
    n += tl + (int)s.pk;
    uint8_t type;
    uint32_t tx0 = c->tx, rx0 = c->rx;
    STEP(S_PUB);
    uint32_t t1 = micros();
    if (io_write(c, pkt, n) != n) { e = "mqtt publish failed: write"; break; }
    do len = read_packet(c, &type, body, sizeof body);  // skip anything that isn't the reply
    while (len >= 0 && (type & 0xF0) != 0x30);
    uint32_t t2 = micros();
    if (len < 2) { e = "kem exchange failed: no reply (is the responder running next to the broker?)"; break; }
    int off = 2 + (body[0] << 8 | body[1]);
    const uint8_t *r = body + off;
    if (len - off != (int)s.ct + 36) { e = "kem exchange failed: reply has the wrong length"; break; }
    STEP(S_DECAPS);
    if (kw_decaps(&s, ss, r)) { e = "decapsulation failed"; break; }
    uint32_t t3 = micros();
    wc_Sha256Hash(ss, s.ss, h);
    if (memcmp(h, r + s.ct, 32)) { e = "kem exchange failed: the shared secrets differ"; break; }
    const uint8_t *en = r + s.ct + 32;
    STEP(S_SERIAL);
    if (x >= MT_KEX_WARMUP)
      Serial.printf("kex,0,%d,%lu,%lu,%lu,%lu,%lu,%lu\n", x - MT_KEX_WARMUP, (unsigned long)(ta - t0),
                    (unsigned long)(t2 - t1), (unsigned long)(t3 - t2),
                    (unsigned long)(en[0] | en[1] << 8 | en[2] << 16 | (uint32_t)en[3] << 24),
                    (unsigned long)(c->tx - tx0), (unsigned long)(c->rx - rx0));
  }
  kw_free(&s);
  wc_FreeRng(&rng);
  return e;
}
#endif

// ---- one connection: timed like mqtt_tls_timer.c's main loop; iter < 0 = warm-up (not printed) ----
static const char *one_connection(WOLFSSL_CTX *ctx, uint16_t port, int iter, int msgs, int group) {
  static const uint8_t disconnect_pkt[] = {0xE0, 0};
  static uint8_t connect_pkt[32];
  static int connect_len = connect_packet(connect_pkt, "pqc-timer", 60);  // the host's 23-byte CONNECT
  rp2040.wdt_reset();
  watchdog_hw->scratch[3] = (uint32_t)iter;
  int free_heap = rp2040.getFreeHeap();
  Conn c;
  const char *e = nullptr;
  uint32_t t0 = micros(), t1 = 0, t2 = 0, t3 = 0, hs_tx = 0, hs_rx = 0, hs_w = 0, hs_r = 0;
  do {
    STEP(S_TCP);
    if (!c.cl.connect(broker, port)) { e = "tcp connect failed (no listener?)"; break; }
    c.cl.setNoDelay(true);
    t1 = micros();
    hs_reset();
    if (ctx) {
      int g = GROUPS[group].id, r;
      if (!(c.tls = wolfSSL_new(ctx))) { e = "wolfSSL_new failed (out of memory?)"; break; }
      wolfSSL_SetIOReadCtx(c.tls, &c); wolfSSL_SetIOWriteCtx(c.tls, &c);
      if (wolfSSL_set_groups(c.tls, &g, 1) != WOLFSSL_SUCCESS || wolfSSL_UseKeyShare(c.tls, g) != WOLFSSL_SUCCESS) {
        e = "group not usable by this wolfSSL build"; break;
      }
      STEP(S_TLS);
      if ((r = wolfSSL_connect(c.tls)) != WOLFSSL_SUCCESS) {
        snprintf(err, sizeof err, "tls handshake failed: %s", tls_err(&c, r)); e = err; break;
      }
    }
    t2 = micros();
    hs_times_t hs = hs_t;  // before the MQTT CONNECT: only the handshake's crypto
    hs_tx = c.tx; hs_rx = c.rx; hs_w = c.io[0]; hs_r = c.io[1];
    uint8_t ack[4];
    int r = 0;
    STEP(S_MQTT);
    if (io_write(&c, connect_pkt, connect_len) != connect_len || (r = io_read_n(&c, ack, 4)) != 4) {
      snprintf(err, sizeof err, "mqtt connect failed: %s", tls_err(&c, r)); e = err; break;
    }
    if (ack[0] != 0x20 || ack[3] != 0) {
      snprintf(err, sizeof err, "mqtt connect refused: CONNACK return code %d", ack[3]); e = err; break;
    }
    t3 = micros();
    STEP(S_SERIAL);
    if (iter == 0 && c.tls) Serial.printf("#suite %s\n", wolfSSL_get_cipher_name(c.tls));
    if (iter >= 0)
      Serial.printf("%d,%.4f,%.4f,%.4f,%.4f,%lu,%lu,%lu,%lu,%lu,%lu,%lu,%lu,%d" HS_FMT "\n", iter, (t1 - t0) / 1e3,
                    (t2 - t1) / 1e3, (t3 - t2) / 1e3, (t3 - t0) / 1e3, (unsigned long)hs_tx, (unsigned long)hs_rx,
                    (unsigned long)(c.tx - hs_tx), (unsigned long)(c.rx - hs_rx), (unsigned long)hs_w,
                    (unsigned long)hs_r, (unsigned long)c.io[0], (unsigned long)c.io[1], free_heap, HS_ARGS(hs));
    if (msgs > 0) e = pipeline(&c, iter, msgs, iter >= 0);
#ifdef MT_KEX_ONLY
    if (!e && cur_kem >= 0 && iter >= 0) e = kem_exchange(&c);
#endif
    STEP(S_TLSCLOSE);
    if (!e) io_write(&c, disconnect_pkt, sizeof disconnect_pkt);
  } while (0);
  STEP(S_TLSCLOSE);
  if (c.tls) { if (!e) wolfSSL_shutdown(c.tls); wolfSSL_free(c.tls); }
  STEP(S_TCPCLOSE);
  c.cl.stop();
  STEP(S_SETUP);
  return e;
}

// ---- one block = the host's run_timer() for one (stage, mode[, scheme, direction]): '#block' .. '#end' ----
static void bench_block(const Block &b) {
  const char *mode = b.mode;
  int iters = b.iters, warm = b.warm, msgs = b.msgs;
  bool tls = strcmp(mode, "plain") != 0, mtls = !strcmp(mode, "mTLS");
  cur_kem = !strcmp(b.stage, "kex") ? b.group : -1;
  uint16_t port = !tls ? PORT_PLAIN : mtls ? PORT_MTLS : PORT_TLS;
  const char *e = nullptr;
  WOLFSSL_CTX *ctx = nullptr;
  peak_heap = cur_heap;
  Serial.printf("#block %s\n", label(b));
  if (msgs > 0) {
    cur_aead = b.aead; down = b.down;
    la_setup(cur_aead);
    Serial.printf("#aead %s (%s), %s, %d B payload + %d B overhead\n", LA[cur_aead].label, LA[cur_aead].lib,
                  down ? "downlink" : "uplink", MT_PAYLOAD, HDR + LA[cur_aead].tag);
    if (!kat_ok && cur_aead) e = "LoRaWAN / AES / Ascon known-answer check failed on this board: not sending";
  }
  if (tls && !e) {
    if (!(ctx = wolfSSL_CTX_new(wolfTLSv1_3_client_method()))) e = "wolfSSL_CTX_new failed (out of memory?)";
    else if (wolfSSL_CTX_load_verify_buffer(ctx, CA_DER, sizeof CA_DER, WOLFSSL_FILETYPE_ASN1) != WOLFSSL_SUCCESS)
      e = "cannot load CA cert: signature algorithm unsupported by this TLS library build?";
    else if (mtls && (wolfSSL_CTX_use_certificate_buffer(ctx, CRT_DER, sizeof CRT_DER, WOLFSSL_FILETYPE_ASN1) != WOLFSSL_SUCCESS ||
                      wolfSSL_CTX_use_PrivateKey_buffer(ctx, KEY_DER, sizeof KEY_DER, WOLFSSL_FILETYPE_ASN1) != WOLFSSL_SUCCESS))
      e = "cannot load client cert/key: signature algorithm unsupported by this TLS library build?";
    if (ctx) {
      wolfSSL_CTX_set_verify(ctx, WOLFSSL_VERIFY_PEER, NULL);
      wolfSSL_CTX_SetIORecv(ctx, cb_recv);
      wolfSSL_CTX_SetIOSend(ctx, cb_send);
    }
  }
  Serial.printf("#lib %s\n", tls ? "wolfSSL " LIBWOLFSSL_VERSION_STRING : "none (plain MQTT)");
  Serial.println("iter,tcp_ms,tls_ms,mqtt_ms,total_ms,hs_tx_B,hs_rx_B,mqtt_tx_B,mqtt_rx_B,hs_writes,hs_reads,writes,reads,"
                 "free_heap_B," HS_COLS);
  if (msgs > 0) Serial.println("msg,iter,idx,seal_us,rtt_us,open_us,tx_B,rx_B");
  for (int i = 0; i < warm + iters && !e; i++) e = one_connection(ctx, port, i - warm, msgs, b.group);
  if (e) Serial.printf("#err %s\n", e);
  if (tls) Serial.printf("#heap %u\n", (unsigned)peak_heap);
  Serial.printf("#stack %lu\n", (unsigned long)stack_peak());
  Serial.println("#end");
  if (ctx) wolfSSL_CTX_free(ctx);
}

static int cur_block;
static int run_block() {
  bench_block(plan(cur_block));
  return 0;
}

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);
  delay(200);
  wolfSSL_SetAllocators(wb_malloc, wb_free, wb_realloc);
  wolfSSL_Init();
  Serial.printf("=== MQTT / TLS 1.3 / mTLS, " STR(MT_SIG) " certificates, X25519MLKEM768 (wolfSSL %s) on " CHIP " ===\n",
                LIBWOLFSSL_VERSION_STRING);
  Serial.printf("CPU clock: %lu MHz\n", (unsigned long)(F_CPU / 1000000u));
  int first = 0;  // after a watchdog reset: report the block that hung, carry on with the next one
  if (rp2040.getResetReason() == RP2040::WDT_RESET && watchdog_hw->scratch[1] == RESUME_MAGIC &&
      watchdog_hw->scratch[0] < N_BLOCKS) {
    first = watchdog_hw->scratch[0] + 1;
    uint32_t step = watchdog_hw->scratch[2];
    Serial.printf("#watchdog %s: hung during %s (connection %ld); no progress for 8 s, the board rebooted; "
                  "continuing with the next block\n", label(plan(first - 1)),
                  step < sizeof STEPS / sizeof *STEPS ? STEPS[step] : "?", (long)(int32_t)watchdog_hw->scratch[3]);
  }
  watchdog_hw->scratch[1] = 0;
  Serial.printf("#config iterations=%d warmup=%d pipe_iterations=%d messages=%d payload_B=%d schemes=%d "
                "sweep_iterations=%d sweep_warmup=%d groups=%d kex_iterations=%d kex_warmup=%d blocks=%d\n", MT_ITERS,
                MT_WARMUP, MT_PIPE_ITERS, MT_MSGS, MT_PAYLOAD, (int)LA_N, MT_SWEEP_ITERS, MT_SWEEP_WARMUP,
                (int)N_GROUPS, MT_KEX_ITERS, MT_KEX_WARMUP, (int)N_BLOCKS);
  kat_ok = la_kat();  // before the session keys: the vectors bring their own
  Serial.printf("#kat LoRaWAN / AES-CMAC / Ascon known-answer checks: %s\n", kat_ok ? "OK" : "FAIL");
  for (int i = 0; i < 32; i++) k_app[i] = rp2040.hwrand32();
  for (int i = 0; i < 16; i++) { k_nwk[i] = rp2040.hwrand32(); k_nwk2[i] = rp2040.hwrand32(); }
  WiFi.mode(WIFI_STA);
  WiFi.noLowPowerMode();
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  for (uint32_t t0 = millis(); WiFi.status() != WL_CONNECTED && millis() - t0 < 30000;) delay(100);
  if (WiFi.status() != WL_CONNECTED) Serial.println("#fatal Wi-Fi: cannot join (2.4 GHz only; check WIFI_SSID / WIFI_PASS)");
  else if (!WiFi.hostByName(BROKER, broker)) Serial.println("#fatal cannot resolve broker " BROKER);
  else {
    Serial.printf("#wifi rssi=%ld dBm channel=%d ip=%s broker=%s\n", (long)WiFi.RSSI(),
                  WiFi.channel(), WiFi.localIP().toString().c_str(), broker.toString().c_str());
    for (int i = 0; i < 4; i++) devaddr[i] = rp2040.hwrand32();
    rp2040.wdt_begin(8000);  // the RP2040's longest; reset per connection and inside every socket wait
    snprintf(topic, sizeof topic, "pqc/pipe/pico-%02x%02x%02x%02x", devaddr[0], devaddr[1], devaddr[2], devaddr[3]);
    for (cur_block = first; cur_block < N_BLOCKS; cur_block++) {
      watchdog_hw->scratch[0] = cur_block; watchdog_hw->scratch[1] = RESUME_MAGIC; STEP(S_SETUP);
      memset(g_stk, STK_PAT, sizeof g_stk);
      run_on_stack(g_stk + sizeof g_stk, run_block);
    }
    watchdog_hw->scratch[1] = 0;
  }
  Serial.println("=== done ===");
}

void loop() { rp2040.wdt_reset(); delay(1000); }
