#!/usr/bin/env bash
# prepare_faest_flat.sh - flatten FAEST's meson tree into plain-cc variant dirs.
#
# FAEST upstream builds with meson + ninja, but all the meson "generation" step
# does is parameter-substitute a handful of .c.in templates. Those generated
# files already exist in FAEST/build_release/ (created once by any meson run;
# they are plain portable C). This script copies, per variant:
#
#   FAEST/*.c *.h                            core implementation
#   FAEST/build_release/<v>.{c,h}            generated variant dispatch
#   FAEST/build_release/parameters.h         generated parameter table
#   FAEST/build_release/faest_aes_{128,192,256}.c
#   FAEST/build_release/<v>/{crypto_sign.c,crypto_sign.h,api.h}   NIST API
#   FAEST/sha3/ (+ opt64)                    Keccak
#
# into FAEST_flat/<v>/ together with a platform config.h:
#   - Linux: a glibc one written below (the meson-generated config.h in
#     build_release/ is macOS-flavoured - arc4random etc. - and must NOT be
#     used on Linux)
#   - macOS: build_release/config.h is reused as-is (it was generated there)
# The result builds with the generic bench harness on BOTH platforms:
#
#   python3 run_reference_benchmarks.py --algos FAEST
#
# IMPORTANT: OpenSSL dev headers are required. The algos.json entry defines
# HAVE_OPENSSL so aes.c uses OpenSSL's hardware AES; without it FAEST falls
# back to pure-C AES and is ~50x slower (verified: 900 ms vs 15 ms per sign).
#   Pi:    sudo apt install libssl-dev
#   macOS: brew install openssl@3, then export CPATH/LIBRARY_PATH (run_all.sh does this)
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/FAEST"
GEN="$SRC/build_release"
OUT="$HERE/FAEST_flat"

VARIANTS="faest_128f faest_128s faest_192f faest_192s faest_256f faest_256s \
faest_em_128f faest_em_128s faest_em_192f faest_em_192s faest_em_256f faest_em_256s"

[ -d "$GEN" ] || { echo "[-] $GEN missing - run 'meson setup build_release && ninja -C build_release' once, or git pull"; exit 1; }

for V in $VARIANTS; do
    T="$OUT/$V"
    rm -rf "$T"
    mkdir -p "$T/sha3"

    cp "$SRC"/*.c "$SRC"/*.h "$T/"
    cp "$GEN/$V.c" "$GEN/$V.h" "$GEN/parameters.h" \
       "$GEN/faest_aes_128.c" "$GEN/faest_aes_192.c" "$GEN/faest_aes_256.c" "$T/"
    cp "$GEN/$V/crypto_sign.c" "$GEN/$V/crypto_sign.h" "$GEN/$V/api.h" "$T/"

    cp "$SRC"/sha3/*.c "$SRC"/sha3/*.h "$T/sha3/"
    cp "$SRC"/sha3/*.inc "$T/sha3/" 2>/dev/null || true
    cp "$SRC"/sha3/*.macros "$T/sha3/" 2>/dev/null || true
    cp "$SRC"/sha3/opt64/*.c "$SRC"/sha3/opt64/*.h "$T/sha3/"
    cp "$SRC"/sha3/opt64/*.inc "$T/sha3/" 2>/dev/null || true
    cp "$SRC"/sha3/opt64/*.macros "$T/sha3/" 2>/dev/null || true

    # Platform config.h
    if [ "$(uname -s)" = "Darwin" ]; then
        # build_release/config.h was meson-generated on macOS - reuse it
        cp "$GEN/config.h" "$T/config.h"
    else
        # Linux/glibc replacement for the meson-generated (macOS) config.h
        cat > "$T/config.h" <<'EOF'
/* config.h for Linux/glibc (replaces meson-generated macOS version).
 * Generated by prepare_faest_flat.sh - do not edit. */
#pragma once
#define HAVE_ALIGNED_ALLOC
#define HAVE_POSIX_MEMALIGN
#define HAVE_MEMALIGN
#define HAVE_EXPLICIT_BZERO
#define HAVE_GETRANDOM
#define HAVE_SYS_RANDOM_H
#define HAVE_SYS_AUXV_H
#define HAVE_ASM_HWCAP_H
#define HAVE_MEMPCPY
EOF
    fi
    echo "[+] $V -> $T"
done

echo "[+] done. Now run:  python3 run_reference_benchmarks.py --algos FAEST --probe-only"
