#!/usr/bin/env bash
# make_uov_keys.sh - the UOV-Ip round 3 key pair for uov_bench, made on the host: keygen holds both keys at once
#   (pk 321,300 B + sk 278,087 B), more RAM than either board has. Same liboqs commit as the Pico's round 3 library
#   (liboqs_bench/make_liboqs_lib.sh LIBOQS_ROUND=3, which clones it), built here for the host with only UOV-Ip.
#   A fixed seed gives the same pair on every machine. The pair is checked (sign, verify, a tampered message fails)
#   before it is written: $IOT_PQC_CACHE/uov-r3/uov_keys.h, const arrays that stay in the Pico's flash.
set -euo pipefail
CACHE=${IOT_PQC_CACHE:-$HOME/.cache/iot-pqc}
SRC="$CACHE/liboqs-r3-src" B="$CACHE/uov-r3-host" OUT="$CACHE/uov-r3"
[ -d "$SRC" ] || { echo "[-] $SRC missing: run LIBOQS_ROUND=3 bash pico/sketches/liboqs_bench/make_liboqs_lib.sh"; exit 1; }
WANT="$(git -C "$SRC" rev-parse HEAD) $(cksum < "$0" | cut -d' ' -f1)"
if [ "$(cat "$OUT/.stamp" 2>/dev/null)" = "$WANT" ]; then echo "[+] UOV-Ip round 3 keys up to date -> $OUT/uov_keys.h"; exit 0; fi
X="" GEN=()   # Windows (Git Bash): .exe names and Ninja
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) X=.exe GEN=(-G Ninja) ;; esac
cmake -Wno-dev ${GEN[@]+"${GEN[@]}"} -S "$SRC" -B "$B" -DCMAKE_BUILD_TYPE=Release -DOQS_MINIMAL_BUILD="SIG_uov_ov_Ip" \
    -DOQS_BUILD_ONLY_LIB=ON -DOQS_USE_OPENSSL=OFF >/dev/null
cmake --build "$B" -j"$(getconf _NPROCESSORS_ONLN 2>/dev/null || nproc)" --target oqs >/dev/null
mkdir -p "$OUT"
cat > "$OUT/keygen.c" <<'EOF'
/* keygen.c (written by make_uov_keys.sh): UOV-Ip round 3 key pair -> stdout as C arrays */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <oqs/oqs.h>
static uint64_t seed = 0x75076040u;  /* fixed: every machine bakes the same pair */
static void rng(uint8_t *x, size_t n) {  /* splitmix64 */
    while (n) {
        uint64_t z = (seed += 0x9E3779B97F4A7C15ull);
        z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull; z = (z ^ (z >> 27)) * 0x94D049BB133111EBull; z ^= z >> 31;
        size_t k = n < 8 ? n : 8; memcpy(x, &z, k); x += k; n -= k;
    }
}
static void arr(const char *name, const uint8_t *p, size_t n) {
    printf("static const unsigned char %s[%zu] __attribute__((aligned(16))) = {", name, n);
    for (size_t i = 0; i < n; i++) printf("%s%u", i ? (i % 40 ? "," : ",\n") : "\n", p[i]);
    printf("\n};\n");
}
int main(void) {
    OQS_init();
    OQS_randombytes_custom_algorithm(rng);
    OQS_SIG *s = OQS_SIG_new(OQS_SIG_alg_uov_ov_Ip);
    if (!s) { fprintf(stderr, "UOV-Ip not in this liboqs\n"); return 1; }
    uint8_t *pk = malloc(s->length_public_key), *sk = malloc(s->length_secret_key), *sig = malloc(s->length_signature);
    uint8_t msg[32] = {0};
    size_t sl;
    if (OQS_SIG_keypair(s, pk, sk) || OQS_SIG_sign(s, sig, &sl, msg, sizeof msg, sk) ||
        OQS_SIG_verify(s, msg, sizeof msg, sig, sl, pk)) { fprintf(stderr, "keygen / sign / verify failed\n"); return 1; }
    msg[0] ^= 1;
    if (OQS_SIG_verify(s, msg, sizeof msg, sig, sl, pk) == OQS_SUCCESS) { fprintf(stderr, "tampered message verified\n"); return 1; }
    printf("// uov_keys.h - generated by pico/sketches/uov_bench/make_uov_keys.sh (%s, liboqs %s): checked on the host\n",
           s->method_name, OQS_version());
    printf("#pragma once\n#define UOV_PK_BYTES %zu\n#define UOV_SK_BYTES %zu\n#define UOV_SIG_BYTES %zu\n",
           s->length_public_key, s->length_secret_key, s->length_signature);
    arr("uov_pk", pk, s->length_public_key);
    arr("uov_sk", sk, s->length_secret_key);
    fprintf(stderr, "[+] %s: pk %zu B, sk %zu B, sig %zu B; sign / verify / tamper OK\n", s->method_name,
            s->length_public_key, s->length_secret_key, sl);
    return 0;
}
EOF
L="$B/lib/liboqs.a"; [ -f "$L" ] || L="$B/lib/oqs.lib"
cc -O2 -I"$B/include" "$OUT/keygen.c" "$L" -lpthread -o "$OUT/keygen$X"
"$OUT/keygen$X" > "$OUT/uov_keys.h.tmp" && mv "$OUT/uov_keys.h.tmp" "$OUT/uov_keys.h"
echo "$WANT" > "$OUT/.stamp"
echo "[+] UOV-Ip round 3 keys -> $OUT/uov_keys.h"
