#!/usr/bin/env bash
# Cross-compile SQIsign round 3 (github.com/SQISign/the-sqisign, the "third-round version") for both Pico CPUs with
# arduino-pico's GCC: the portable ref build with 32-bit field arithmetic (GF_RADIX=32) and mini-GMP, all three
# levels (p324_3 = I, p500_27 = III, p664_17 = V). Packaged as a precompiled Arduino library:
#   $IOT_PQC_CACHE/arduino-libs/sqisign/src/{cortex-m0plus,cortex-m33}/libsqisign.a + headers
# The library's own randombytes (randombytes_system.c: OS entropy) is emptied: the sketch supplies randombytes().
set -euo pipefail
CACHE=${IOT_PQC_CACHE:-$HOME/.cache/iot-pqc}
REV=${SQISIGN_REV:-f417ebd}   # round 3 (6d01770, 1 Sep 2026) + a test-only fix
SRC="$CACHE/sqisign-src" LIB="$CACHE/arduino-libs/sqisign" LEVELS="p324_3 p500_27 p664_17"
[ -d "$SRC" ] || git clone -q https://github.com/SQISign/the-sqisign.git "$SRC"
git -C "$SRC" checkout -q -f "$REV"
# bare metal has no OS entropy: randombytes_system.c doesn't compile there, and the sketch supplies randombytes()
echo '/* Pico build: randombytes() comes from the sketch (hardware RNG) */' > "$SRC/src/common/generic/randombytes_system.c"
GCC=""   # arduino-pico's bundled toolchain (macOS, Linux, Windows paths)
for d in "$HOME"/Library/Arduino15/packages/rp2040/tools/pqt-gcc/*/bin \
         "$HOME"/.arduino15/packages/rp2040/tools/pqt-gcc/*/bin \
         "$HOME"/AppData/Local/Arduino15/packages/rp2040/tools/pqt-gcc/*/bin; do
    [ -x "$d/arm-none-eabi-gcc" ] && GCC="$d"
done
[ -n "$GCC" ] || { echo "[-] arduino-pico toolchain not found: arduino-cli core install rp2040:rp2040"; exit 1; }
X="" GEN=()   # Windows (Git Bash): .exe names and Ninja
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) X=.exe GEN=(-G Ninja) ;; esac
DEFS="-DSQISIGN_SINGLE_THREADED"   # upstream's switch for embedded targets: no _Thread_local (bare metal has no TLS)
STAMP="$LIB/.iot-pqc-build"
WANT="$(git -C "$SRC" rev-parse HEAD) $("$GCC/arm-none-eabi-gcc$X" -dumpversion) $LEVELS $DEFS"
if [ "$(cat "$STAMP" 2>/dev/null)" = "$WANT" ]; then echo "[+] SQIsign Arduino library up to date -> $LIB"; exit 0; fi
rm -rf "$LIB" && mkdir -p "$LIB/src"
for MCU in cortex-m0plus cortex-m33; do
    case $MCU in   # must match arduino-pico's boards.txt toolchain options, or the link fails
        cortex-m0plus) CPU="-mcpu=cortex-m0plus -mthumb -march=armv6-m" ;;
        cortex-m33)    CPU="-mcpu=cortex-m33 -mthumb -march=armv8-m.main+fp+dsp -mfloat-abi=softfp -mcmse" ;;
    esac
    B="$CACHE/sqisign-build-$MCU"
    rm -rf "$B"
    cmake -Wno-dev ${GEN[@]+"${GEN[@]}"} -S "$SRC" -B "$B" -DCMAKE_BUILD_TYPE=Release -DSQISIGN_BUILD_TYPE=ref -DGF_RADIX=32 \
        -DGMP_LIBRARY=MINI -DENABLE_TESTS=OFF -DENABLE_STRICT=OFF -DCMAKE_SYSTEM_NAME=Generic -DCMAKE_SYSTEM_PROCESSOR="$MCU" \
        -DCMAKE_C_COMPILER="$GCC/arm-none-eabi-gcc$X" -DCMAKE_AR="$GCC/arm-none-eabi-ar$X" \
        -DCMAKE_RANLIB="$GCC/arm-none-eabi-ranlib$X" -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
        -DCMAKE_C_FLAGS="$CPU -Os -ffunction-sections -fdata-sections $DEFS" >/dev/null
    cmake --build "$B" -j"$(getconf _NPROCESSORS_ONLN 2>/dev/null || nproc)" \
        --target $(for l in $LEVELS; do printf 'sqisign_%s_nistapi ' "$l"; done) >/dev/null
    O="$B/objs" && rm -rf "$O" && mkdir -p "$O"
    for a in $(find "$B/src" -name '*.a' | grep -v test); do   # one archive; object names prefixed by their library
        (cd "$O" && mkdir -p x && cd x && "$GCC/arm-none-eabi-ar$X" x "$a" && for o in *; do mv "$o" "../$(basename "$a" .a)_${o%.obj}.o"; done)  # bare-metal CMake names them .obj
    done
    rm -rf "$O/x"
    mkdir -p "$LIB/src/$MCU" && "$GCC/arm-none-eabi-ar$X" rcs "$LIB/src/$MCU/libsqisign.a" "$O"/*.o
done
for l in $LEVELS; do cp "$SRC/src/nistapi/$l/api.h" "$LIB/src/sqisign_api_$l.h"; done
cp "$(find "$SRC" -name sqisign_namespace.h | head -1)" "$LIB/src/"
cat > "$LIB/src/sqisign.h" <<'EOF'
// sqisign.h - SQIsign round 3 for the Pico: -DSQISIGN_LVL1 / LVL3 / LVL5 picks the level (default I)
#pragma once
#define SQISIGN_BUILD_TYPE_REF
#define ENABLE_SIGN
#if defined(SQISIGN_LVL5)
#define SQISIGN_VARIANT p664_17
#include "sqisign_api_p664_17.h"
#elif defined(SQISIGN_LVL3)
#define SQISIGN_VARIANT p500_27
#include "sqisign_api_p500_27.h"
#else
#define SQISIGN_VARIANT p324_3
#include "sqisign_api_p324_3.h"
#endif
EOF
cat > "$LIB/library.properties" <<EOF
name=sqisign
version=3.0.0
author=The SQIsign team
maintainer=IoT-PQC (generated by pico/sketches/sqisign_bench/make_sqisign_lib.sh)
sentence=SQIsign round 3 (ref, GF_RADIX=32, mini-GMP) cross-compiled for RP2040 / RP2350
paragraph=$REV
category=Other
url=https://sqisign.org
architectures=rp2040
precompiled=true
ldflags=-lsqisign
EOF
echo "$WANT" > "$STAMP"
echo "[+] SQIsign $REV ($LEVELS) for cortex-m0plus + cortex-m33 -> $LIB"
