#!/usr/bin/env bash
# update_src.sh - rebuild src/ from a FAEST release (github.com/faest-sign/faest-ref) as its meson build does for a
# 32-bit target:   bash pico/sketches/faest_bench/update_src.sh [tag]      (default v3.0.0, NIST round 3)
# Clones the tag into $IOT_PQC_CACHE/faest-<tag>, runs meson once (it generates the parameter files and the VOLE
# multiplication tables), then copies into src/:
#   - the library sources with sha3/plain32 (meson's choice when pointers are 32-bit), the generated faest_<v>.{c,h},
#     faest_aes_*.c, parameters.h and tables/ (static const: they stay in flash);
#   - per variant v: the NIST API as api__<v>.h and crypto_sign__<v>.c, compiled only with -DPICO_VARIANT_<v>;
#   - .inc / .macros files renamed *_inc.h / *_macros.h (arduino-cli copies only source and header extensions).
# Every .c starts with faest_config_pico.h: randombytes() from the sketch (PQClean signature), no OS RNG.
set -euo pipefail
TAG=${1:-v3.0.0}
HERE="$(cd "$(dirname "$0")" && pwd)"
C="${IOT_PQC_CACHE:-$HOME/.cache/iot-pqc}/faest-$TAG"
VARIANTS="128f 192f 256f em_128f"
[ -d "$C" ] || git clone -q --branch "$TAG" https://github.com/faest-sign/faest-ref.git "$C"
[ -f "$C/build_release/parameters.h" ] || { (cd "$C" && meson setup build_release -Dbuildtype=release >/dev/null && \
    ninja -C build_release >/dev/null); }
S="$HERE/src" KEEP="$(mktemp -d)"
cp "$S"/ino__*.h "$KEEP/"        # the per-variant sketches are ours, not FAEST's: keep them
rm -rf "${S:?}" && mkdir -p "$S/tables" && cp "$KEEP"/ino__*.h "$S/"
B="$C/build_release"
cp "$C"/*.h "$C"/{aes,bavc,compat,cpu,faest_impl,fields,instances,owf,random_oracle,randomness,universal_hashing,utils,vole}.c "$S/"
cp "$B"/parameters.h "$B"/faest_aes_{128,192,256}.c "$S/"
for v in $VARIANTS; do
    cp "$B/faest_$v.c" "$B/faest_$v.h" "$S/"
    cp "$B/faest_$v/api.h" "$S/api__$v.h"
    { echo "#if defined(PICO_VARIANT_$v)  /* faest_$v/crypto_sign.c, generated by meson */"
      cat "$B/faest_$v/crypto_sign.c"; echo "#endif"; } > "$S/crypto_sign__$v.c"
done
cp "$B"/tables/*.h "$S/tables/"
cp "$C"/sha3/*.h "$C"/sha3/KeccakHash.c "$C"/sha3/KeccakSponge.c "$C"/sha3/plain32/* "$S/"
cp "$C/sha3/KeccakSponge.inc" "$S/KeccakSponge_inc.h"
mv "$S/PlSnP-Fallback.inc" "$S/PlSnP-Fallback_inc.h"
{ echo "/* api.h: differs between parameter sets; the build picks one with -DPICO_VARIANT_<v> */"
  first=1; for v in $VARIANTS; do
      [ $first = 1 ] && echo "#if defined(PICO_VARIANT_$v)" || echo "#elif defined(PICO_VARIANT_$v)"
      echo "#include \"api__$v.h\""; first=0
  done; echo "#endif"; } > "$S/api.h"
cat > "$S/faest_config_pico.h" <<'EOF'
#ifndef FAEST_CONFIG_PICO_H
#define FAEST_CONFIG_PICO_H
#define HAVE_RANDOMBYTES
#define PQCLEAN
#ifndef NDEBUG
#define NDEBUG
#endif
#endif
EOF
for f in "$S"/*.c; do
    { echo '#include "faest_config_pico.h"'; sed -e 's/"KeccakSponge.inc"/"KeccakSponge_inc.h"/' -e 's|#include "sha3/|#include "|' \
        -e 's/"PlSnP-Fallback.inc"/"PlSnP-Fallback_inc.h"/' "$f"; } > "$f.tmp" && mv "$f.tmp" "$f"
done
sed -i.bak -e 's/"PlSnP-Fallback.inc"/"PlSnP-Fallback_inc.h"/' -e 's|#include "sha3/|#include "|' -e 's|#include "\.\./|#include "|' "$S"/*.h && rm -f "$S"/*.bak  # sha3/ is flattened
echo "[+] FAEST $TAG ($(git -C "$C" rev-parse --short HEAD)) -> $S: $(ls "$S" | wc -l | tr -d ' ') files, variants $VARIANTS"
